// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bighuangbee/basic-service/internal/conf"
	"github.com/bighuangbee/basic-service/internal/data"
	"github.com/bighuangbee/basic-service/internal/module/account/app"
	"github.com/bighuangbee/basic-service/internal/module/account/repo"
	"github.com/bighuangbee/basic-service/internal/module/account/service"
	"github.com/bighuangbee/basic-service/internal/protocol"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func autoWireApp(bootstrap *conf.Bootstrap, logger log.Logger, helper *log.Helper) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	iAccountRepo := repo.NewAccountRepo(dataData, helper, bootstrap)
	accountService := service.NewAccountService(iAccountRepo, logger, bootstrap)
	accountServer := app.NewAccountApp(accountService, helper)
	pbServer := &protocol.PbServer{
		Account: accountServer,
	}
	server := protocol.NewHTTPServer(bootstrap, logger, pbServer, dataData)
	grpcServer := protocol.NewGRPCServer(bootstrap, logger, pbServer)
	kratosApp := newApp(bootstrap, logger, server, grpcServer)
	return kratosApp, func() {
		cleanup()
	}, nil
}
